services:
  mysql:
    image: mysql:8.0
    container_name: mysql_docker
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  dbgate:
    image: dbgate/dbgate:latest
    container_name: db_ui
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - dbgate_data:/root/.dbgate

volumes:
  mysql_data:
  dbgate_data: